### ISSUE TITLE
Expand ABI support by replacing opaque items

### ISSUE THREAD

**Issue by celinval** [rust-lang/project-stable-mir#58]
We are adding some basic support to function ABI and type layout in this PR: https://github.com/rust-lang/rust/pull/119094, however, some information was left as Opaque for now.

We still need to expand the following:

```[tasklist]
### Tasks
- [ ] Add information about `Scalar`.
- [ ] Expand PassMode attributes.
- [ ] Add information about `Primitive`
```
