### ISSUE TITLE
Initial Use Case: Port MiniRust

### ISSUE THREAD

**Issue by celinval** [rust-lang/project-stable-mir#66]
@RalfJung suggested that the MiniRust translation module is a good candidate for us to assess the impact of migrating to StableMIR.

This issue tracks the work needed to port MiniRust. I believe we can migrate a few modules at a time:

```[tasklist]
### Tasks
- [ ] Update MiniRust a newer nightly version
- [ ] Migrate `minimize::ty` module
- [ ] Migrate `minimize::rvalue` module
- [ ] Migrate the rest of the code
```

**Comment by RalfJung** [comment]
> Update MiniRust a newer nightly version

That part is done now, I wanted to do this anyway.

**Comment by celinval** [comment]
I created https://github.com/minirust/minirust/pull/166 to migrate `rvalue`.
